version: "3.8"
services:
  mongodb:
    image: mongo:5.0.2
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sounak08
      - MONGO_INITDB_ROOT_PASSWORD=sounak0077
    ports:
      - "${PORT-27017:27017}"
    volumes:
      - db:/data/db
  api:
    depends_on:
      - mongodb
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mongodb
      - DB_USER=sounak08
      - DB_PASSWORD=sounak0077
      - DB_NAME=anyfin
      - DB_PORT=27017
      - SECRET=superSecret
      - PORT=8080
    stdin_open: true
    tty: true
volumes:
  db: